Repository Bitmessage/PyBitmessage, pull requests merged in 2018-03, with the labels that each got.

#1150 Startup problem in openwrt
  src/depends.py
  src/pyelliptic/openssl.py
Labels: bug

#1156 Translation update ja
  src/translations/bitmessage_ja.qm
  src/translations/bitmessage_ja.ts
Labels: enhancement

#1151 Updated license years
  LICENSE
Labels: legal

#1145 Do not duplicate avatar in address column of Address book
  src/bitmessageqt/foldertree.py
Labels: bug

#1158 backticks problematic
  packages/unmaintained/puppy.sh
Labels: formatting

#1169 Random (shuffle, sample, randrange) in helper random.
  src/helper_random.py
Labels: developers, refactoring

#1174 replace all random.xxx with helper random function
  src/class_sqlThread.py
  src/helper_msgcoding.py
  src/helper_random.py
  src/helper_startup.py
  src/network/asyncore_pollchoose.py
  src/network/bmproto.py
  src/network/connectionchooser.py
  src/network/connectionpool.py
  src/network/downloadthread.py
  src/network/tcp.py
  src/randomtrackingdict.py
Labels: formatting

#1167 Prevent settingsDialog from setting dontconnect = false
  src/bitmessageqt/__init__.py
Labels: bug

#1172 Foldertree flake8
  src/bitmessageqt/foldertree.py
Labels: formatting

#952 Handle exceptions from python without ipv6 support
  src/protocol.py
Labels: bug

#1179 Consider to use defaults for 'apiport' and 'apiinterface'
  src/bmconfigparser.py
Labels: bug

#1188 shorten sentence , offer beamstat link
  README.md
Labels: documentation

#1148 Do not try to connect namecoin if dontconnect set in config (#1146)
  src/bitmessageqt/__init__.py
Labels: bug
