Repository Bitmessage/PyBitmessage, pull requests merged in 2018-06, with the labels that each got.

#1259 enable delayed POW checks
  src/protocol.py
Labels: enhancement

#1250 Fixed: Style and lint violations in src/bitmessageqt/__init__.py
  src/bitmessageqt/__init__.py
Labels: developers, formatting

#1280 Returning bitmessageqt package back to normal
  src/bitmessageqt/__init__.py
Labels: developers, formatting

#1264 Fixed: Style and lint violations for three more of the worst violatin…
  src/bitmessageqt/__init__.py
  src/network/bmproto.py
  src/network/tcp.py
Labels: developers, formatting

#1281 flake8: state
  src/state.py
Labels: developers, formatting

#1290 Translation update ru
  src/translations/bitmessage_ru.qm
  src/translations/bitmessage_ru.ts
Labels: translation

#1291 Returned logger setting to debug
  src/debug.py
Labels: bug
