Repository Bitmessage/PyBitmessage, pull requests merged in 2018-07, with the labels that each got.

#1294 No need to import namecoin early because it's really used only in Qt UI
  src/bitmessageqt/__init__.py
  src/helper_startup.py
Labels: enhancement

#1295 Fix an issue from #1153 for setup without plugins package
  src/bitmessageqt/__init__.py
Labels: bug

#1303 Confirmation for network switch
  src/bitmessageqt/__init__.py
Labels: usability

#1323 Travis should test mandatory dependencies
  .travis.yml
  checkdeps.py
Labels: developers, test

#1326 Additional fix for #1316
  checkdeps.py
  src/depends.py
Labels: bug
