Repository Bitmessage/PyBitmessage, pull requests merged in 2018-04, with the labels that each got.

#1193 Testing mode for bitmessagemain
  src/bitmessagemain.py
Labels: developers

#1197 Memory leak (kind of) fix
  src/network/tcp.py
Labels: bug

#1196 Obvious fix for #1194
  src/bitmessageqt/foldertree.py
Labels: bug

#1202 Shutdown fixes
  src/shutdown.py
Labels: bug

#1206 helper_generic formating
  src/helper_generic.py
Labels: formatting

#1218 fix logic bug in enableGUI implementation
  src/bitmessagemain.py
Labels: bug

#1217 Added some communication channels to README.md
  README.md
Labels: documentation
